### ISSUE TITLE
About function" get_consistent_masks"

### ISSUE THREAD

**Issue by Chao86** [B1ueber2y/TrianFlow#1]
hello,  i have a qustion about your function "get_consistent_masks",
`# flow consistency condition
            bwd_consist_bound = torch.max(self.flow_consist_beta * self.get_flow_norm(optical_flow_rev), torch.from_numpy(np.array([self.flow_consist_alpha])).float().to(optical_flow_rev.get_device()))
            fwd_consist_bound = torch.max(self.flow_consist_beta * self.get_flow_norm(optical_flow), torch.from_numpy(np.array([self.flow_consist_alpha])).float().to(optical_flow.get_device()))`
, however in the referenced paper"UnFlow: Unsupervised Learning of Optical Flow
with a Bidirectional Census Loss" the  occclusion mask is defined as follows: 
![image](https://user-images.githubusercontent.com/44365146/82627380-de406180-9c1c-11ea-8efa-963cd0685f56.png)
I wonder the flow consistency condition should be
 ` bwd_consist_bound = self.flow_consist_beta * (self.get_flow_norm(optical_flow_rev)+self.get_flow_norm(fwd2bwd_flow))+torch.from_numpy(np.array([self.flow_consist_alpha])).float().to(optical_flow_rev.get_device())
            fwd_consist_bound = self.flow_consist_beta * (self.get_flow_norm(optical_flow)+self.get_flow_norm(fwd2bwd_flow))+torch.from_numpy(np.array([self.flow_consist_alpha])).float().to(optical_flow.get_device())`
Waiting for your reply.
Thank you

**Comment by thuzhaowang** [comment]
We followed the GeoNet [61] for the formulation of flow forward-backward consistency, as mentioned in section 3.1 of our paper. The ideas about flow consistency of UnFlow and GeoNet are quite similar, while they differ in the implementation.

**Comment by Chao86** [comment]
> We followed the GeoNet [61] for the formulation of flow forward-backward consistency, as mentioned in section 3.1 of our paper. The ideas about flow consistency of UnFlow and GeoNet are quite similar, while they differ in the implementation.
