### ISSUE TITLE
How long does it take to train networks?

### ISSUE THREAD

**Issue by demonleach** [B1ueber2y/TrianFlow#10]
Thank you for sharing codes!

How long does it take to train networks for each stage?
I also want to know your environment.

Thank you in advance.

**Comment by thuzhaowang** [comment]
You can find the environmental setting in the requirements.txt. For the optical flow network, it usually takes ~36h in a single Titan Xp card and the second and third stages need ~24h for each. For nyu dataset it takes longer time thanks to much more training data.

**Comment by demonleach** [comment]
@thuzhaowang Thank you for your reply!
