### ISSUE TITLE
Issue in intrinsic scaling

### ISSUE THREAD

**Issue by hyBlue** [B1ueber2y/TrianFlow#12]
https://github.com/B1ueber2y/TrianFlow/blob/05c404ff8d6a58d96ba3b980190da426ca94c25c/core/dataset/kitti_prepared.py#L87-L90

Hi, thanks for great work. 
While reproducing your works, it seems having a minor mistake. 

I think the function above should be
```
 K[0,:] = K[0,:] * img_hw_new[1] / img_hw_orig[1] 
 K[1,:] = K[1,:] * img_hw_new[0] / img_hw_orig[0] 
```
because img_hw contains (height, width) and K[0, :] is related to the width, and K[1, :] is related to the height. Isn't it?

**Comment by liyingliu** [comment]
I just found the same issue too. @hyBlue I guess you are right.

**Comment by thuzhaowang** [comment]
@hyBlue @liyingliu  Thanks for reporting this issue. It's fixed now.
