### ISSUE TITLE
To evaluate the optical flow estimation on KITTI 2015

### ISSUE THREAD

**Issue by csl1994** [B1ueber2y/TrianFlow#2]
Hello, I have three questions about flow.
1.There is nothing in result_dir after executed the commond, commond as follow
 "python test.py --config_file ./config/kitti.yaml --gpu 0 --mode flow_3stage --task kitti_flow --pretrained_model ./model/kitti_flow.pth --result_dir ./save/flow/"
2.What are the meanings of these indicators？
[EVAL] [KITTI 2015]
       epe,    epe_noc,    epe_occ,   epe_move, epe_static, move_err_rate, static_err_rate,   err_rate 
  725.6288,   725.6288,     0.0000,   711.0284,   725.9844,     0.0136,     0.0112,     0.0112 
3.Could the dataset pre-processing be clearer? eg.KITTI 2015
Waiting your reply.
THX!

**Comment by thuzhaowang** [comment]
1. To save the flow predictions, you need to set the "write_img" variable to True in function eval_flow_avg in test_kitti_2015.
2. These are some metrics to evaluate the flow prediction. For example, "epe" for end-point-error, and "epe-noc" for end-point-error of non-occluded regions, "epe-static" for end-point-error of static scenes, i.e. excluding moving objects, "err_rate" for error rate of flow prediction.
3. I'm not very sure about your question. But the KITTI 2015 dataset needs no pre-processing. You only need to download and unzip it, then set the right path in your config file, specifically "gt_2015_dir".

**Comment by csl1994** [comment]
Thanka for your reply
