### ISSUE TITLE
TUM dataset model

### ISSUE THREAD

**Issue by csl1994** [B1ueber2y/TrianFlow#3]
Could you provide the pre-trained model of TUM dataset or some experiment details ? I want to reproduce the experiment as shown in figure 6.
Thank you.

**Comment by thuzhaowang** [comment]
You can find the pre-trained tum model in https://drive.google.com/drive/folders/1rPXlK9bJpjU0OQH5leDCvyb0FcL5jlUk?usp=sharing.

**Comment by csl1994** [comment]
Thanks

**Comment by csl1994** [comment]
How to modify the code for TUM in infer_vo.py？
code: cfg['dataset'] = 'kitti_odo' --->cfg['dataset'] = 'nuyv2' ?

**Comment by thuzhaowang** [comment]
Yeah for odometry inference on tum dataset you could use the nyuv2 configuration file instead and set the cfg['dataset'] to 'nuyv2'. Also you may need to change the dataloading in infer_vo.py a little to read the data correctly.
