### ISSUE TITLE
About occlusion mask

### ISSUE THREAD

**Issue by Chao86** [B1ueber2y/TrianFlow#4]
hi,
In your code ,
`# get occlusion masks
     img2_visible_masks, img1_visible_masks = self.get_visible_masks(optical_flows, optical_flows_rev)
  # get consistent masks
     img2_consis_masks, img1_consis_masks, fwd_flow_diff_pyramid, bwd_flow_diff_pyramid = self.get_consistent_masks(optical_flows, optical_flows_rev)
 # get final valid masks 
    img2_valid_masks, img1_valid_masks = [], []
    for i, (img2_visible_mask, img1_visible_mask, img2_consis_mask, img1_consis_mask) in enumerate(zip(img2_visible_masks, img1_visible_masks, img2_consis_masks, img1_consis_masks)):
            img2_valid_masks.append(img2_visible_mask * img2_consis_mask)
            img1_valid_masks.append(img1_visible_mask * img1_consis_mask)`
I wonder the difference between final valid masks and occlusion masks. In your code ,you use valid masks to compute pixel loss and ssim loss,  why not use the occlusion masks to compute pixel loss and ssim loss ?
Except for taht, how to set suitable "self.flow_consist_alpha" and "cfg.h_flow_consist_beta" parameters? can you share your experience?
Thank you .

**Comment by thuzhaowang** [comment]
Both the visible mask and consistent mask have the ability to mask out occlusion in some extent, while the consistent mask (score) could give us a quantitative score for matches also in non-occluded regions. Thus we mainly use the consistency check to sample reliable matches and use visible mask to handle occlusion. For alpha and beta parameters, we use the default setting as used in GeoNet [61].
