### ISSUE TITLE
Reproduce KITTI experiment

### ISSUE THREAD

**Issue by shiba24** [B1ueber2y/TrianFlow#7]
Hello, thank you for sharing the code.
I'm now trying to reproduce the KITTI experiment (three step training) and facing some points that are not clear.
Let me first ask you some points:

- image directory in the kitti 2012 vs kitti 2015
By default, when downloaded, stereo data has the following structures:

```
kitti_stereo/kitti_2012/training/image_0/
kitti_stereo/kitti_2012/training/image_1/
kitti_stereo/kitti_2015/training/image_2/
kitti_stereo/kitti_2015/training/image_3/
```

but looking at your code here, `image_2` is hardcoded. I guess this only works for 2015 dataset - which of `image_0` or `image_1` did you use for 2012 dataset?
https://github.com/B1ueber2y/TrianFlow/blob/master/core/dataset/kitti_2012.py#L25-L26

- Another thing that I found is this `calib_cam_to_cam` should be `calib`.
https://github.com/B1ueber2y/TrianFlow/blob/master/core/dataset/kitti_2012.py#L27

**Comment by thuzhaowang** [comment]
Thanks for pointing it out. We use the colored left image for all the kitti dataset. For kitti 2012, it should be 'color_0'. We rename some folders of the kitti 2012 to have the same interface with kitti 2015. And yes it would be 'calib' for kitti 2012.
