### ISSUE TITLE
problem  about scale consistency

### ISSUE THREAD

**Issue by hello7623** [B1ueber2y/TrianFlow#8]
Thank for  your pretty work, it gives me a lot of inspiration,but i have some doubts:
In the paper ，It is said that the consistency of scale is achieved by  aligning the depth to the pose(translation), but,I wonder that, the pose is  gained from 8 points method, while the 8 points methods don't satisfied the scale consistency,.Do you mean that it is for depth and pose for subsequent reprojection ? So the consistency is through $L_{pd}$ Another problem is that it seems that PWC-Net is a supervision method, not unsupervision, so what specific method for the estimation of optical flow?

**Comment by thuzhaowang** [comment]
1. The translation length from 8-Point algorithm is always a unit (up-to-scale). So for the training stage, we align the predicted depth to the pose (triangulation depth) to make the depth and pose consistent for calculating the loss. For the inference stage of visual odometry, we need the scale consistency over the whole sequence thus we align the scale of pose translation to the predicted depth.
2. Yes PWC-Net is originally a supervised optical flow method, but its architecture could be used for unsupervised optical flow training.

**Comment by hello7623** [comment]
A really nice work , I have known it , thanks a lot!

**Comment by pleasegostraight** [comment]
>     1. The translation length from 8-Point algorithm is always a unit (up-to-scale). So for the training stage, we align the predicted depth to the pose (triangulation depth) to make the depth and pose consistent for calculating the loss. For the inference stage of visual odometry, we need the scale consistency over the whole sequence thus we align the scale of pose translation to the predicted depth.
> 
>     2. Yes PWC-Net is originally a supervised optical flow method, but its architecture could be used for unsupervised optical flow training.

Hi, may I ask how to align the scale of pose translation to the predicted depth?
